# This is a basic workflow to help you get started with Actions

name: Distribute framework to github distribution

# Controls when the action will run. 
on:
   # Enable manual dispatch of the workflow
  workflow_dispatch:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create_release"
  create_release:
    # The type of runner that the job will run on
    runs-on: macos-10.15
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out source repository
        uses: actions/checkout@v2

      # Run dependency fetch. e.g: cocoapods if needed.

      - name: Setup Xcode version
        # You may pin to the exact commit or the version.
        # uses: maxim-lobanov/setup-xcode@39fba9d7d77a658123787968f124e64e41ee38a1
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          # Version of Xcode to use
          xcode-version: "latest-stable"
          
      # Build framework
      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v1.4
        with: 
          target: TestFramework
          platforms: ios
          configuration: release 
          
      # Upload build artifacts
      - name: Upload xcframework
        uses: actions/upload-artifact@v2
        with:
          name: xcframework
          path: "./*.xcframework"
