name: Run Tests

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2
     
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "latest-stable"

      - name: Run tests with Xcodebuild
        run: |
          xcodebuild test -enableCodeCoverage YES -quiet -project TestFramework.xcodeproj -scheme TestFramework -destination 'platform=iOS Simulator,name=iPhone 11'
