name: Run Tests

on:
  pull_request:
    types: [ opened, synchronize ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
     
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "latest-stable"
